/* Query 2: Perform Simple Data Transformations Using SQL
Learners should perform the following transformations using SQL queries:
2.	Data Exploration Queries
○	Count the number of restaurants in each city.
○	Find the top 5 cities with the highest number of orders.
○	Calculate the total revenue generated by each restaurant.*/

select * from zomato_orders;
select * from zomato_restaurants;

-- 1.
select city, count(*) as no_city from zomato_restaurants
group by city;

-- 2.
select zr.city, count(zo.order_id) as no_orders from zomato_restaurants zr
join zomato_orders zo on zr.restaurant_id = zo.restaurant_id
group by zr.city
order by no_orders desc
limit 5;

-- 3. 
select zr.restaurant_name, sum(zo.total_cost) as total_revenue from zomato_restaurants zr
join zomato_orders zo on zr.restaurant_id = zo.restaurant_id
group by zr.restaurant_name
order by total_revenue desc;